### ISSUE TITLE
Error in loading file, connection timed out

### ISSUE THREAD

**Issue by ADvorkinGheva** [reactome-fi/CytoscapePlugIn#11]
Dear Sir/Madam,

I have been using Reactome FI plugin very extensively for the last few years. However, when I tried to run it now using "Gene Set/Mutation Analysis" module and pasting the list of genes into the "Enter" window, the network construction took a very long time and eventually failed with the display of the following message: 
"Error in Loading File: Connection timed out: connect"

Since then I have updated both the Reactome FI plugin and the Cytoscape, and the attempts to run the Reactome FI keep failing with the same error message.

Please, advise on how to solve this situation.

Thank you very much for your help!

Sincerely,
Anna

**Comment by guanmingwu** [comment]
Hi Anna,

I hope this issue has been resolved. If not, please let us know.

Thanks for your interesting in ReactomeFIViz.

Guanming

**Comment by ADvorkinGheva** [comment]
Dear Guanming,

Thank you very much for your email.
I have closed the issue because suddenly the plugin succeeded in running,
so I didn't need help with it.

Regards,
Anna
