### ISSUE TITLE
Problems met while using ReactomeFI in Cytoscape

### ISSUE THREAD

**Issue by NewTearingHeaven** [reactome-fi/CytoscapePlugIn#12]
Hello, recently when I'm using cytoscape's app Reactome FI' function :Gene set. After I submit the requests, I get an error showing "Error in loading file: Connection refused: connect". And when I try the function Reactome pathways, it shows no reply. 
Finally, I go to the website "https://reactome.org/download-data", and find that all the Functional Interactions(2019, 2018, 2017, 2016) can't be downloaded. I wonder if there's something wrong with my computer or internet or the source?

**Comment by guanmingwu** [comment]
Apparently there is an issue with the AWS server hosting the RESTful API for ReactomeFIViz, which blocks ports 80 and 8080. We are working on fixing the issue. Sorry for any inconvenience!

**Comment by guanmingwu** [comment]
The server issue should be fixed now. Please be aware you may get some issues with downloading using Safari with MacOS. If you are under Mac, better use Chrome.

**Comment by NewTearingHeaven** [comment]
Thank you very much! It's working now.
