### ISSUE TITLE
connection timed out?

### ISSUE THREAD

**Issue by JenniferZhung** [reactome-fi/CytoscapePlugIn#3]
Hi,
Why does it always show that"connection timed out" when I use "Gene set/mutation Analysis "?
And I want to load the Reactome Pathways ,but it showed nothing after a VERY long time running...
I am sure that my internet is well. 
So sad..

**Comment by guanmingwu** [comment]
The web service servers used to provide contents are under maintenance this weekend. They should be back Monday. Sorry for the inconvenience!

**Comment by xiweiwu** [comment]
I got the same error for the past few months. Is the server down again recently?

**Comment by guanmingwu** [comment]
Just checked. The server works fine. Could you check if your computer can access the following URL: http://cpws.reactome.org (Note: http, not https)?

**Comment by xiweiwu** [comment]
Thanks for the reply. I can access the web site. The problem is solved after I upgrade to the latest version of Cytoscape and ReactomeFI.
