### ISSUE TITLE
Error in overlay gene scores: 1

### ISSUE THREAD

**Issue by Tato14** [reactome-fi/CytoscapePlugIn#7]
I perform pathway enrichement and, after loading a DE pathway I tried to populate with gene scores. I try to upload a txt file with gene names in first column and logFC in second column but I got this error. Any idea why is this happening?

Cytoscape 3.7.2, ReactomeFIPligun 7.2.0

**Comment by guanmingwu** [comment]
Could you please post the error message? If it is possible, could you please share your txt file too?

**Comment by Tato14** [comment]
Hi

The error message is in the title, nothing else. Here is an screenshot:
![Screenshot from 2020-02-03 08-17-35](https://user-images.githubusercontent.com/33808607/73634282-25e8b080-4661-11ea-840e-a6481c09d535.png)

Here is the txt file: 
[TCGA_LUSC_DEG_cytoscape_reactome.txt](https://github.com/reactome-fi/CytoscapePlugIn/files/4146729/TCGA_LUSC_DEG_cytoscape_reactome.txt)

Thanks

**Comment by guanmingwu** [comment]
The score file should be tab delimited. Could you make sure it is?

**Comment by Tato14** [comment]
It seems it was not tab delimited. Sorry for not assessing this before. Closing the issue.
