### ISSUE TITLE
Graphical Model Analysis error

### ISSUE THREAD

**Issue by Tato14** [reactome-fi/CytoscapePlugIn#8]
Hi,

I am trying to work with Grpahical Model analysis on the LUSC TCGA cancer dataset. I managed to input the [CNV](https://drive.google.com/open?id=155zLxQSr-kNOlXV0zKPexRZlnkyUQ9d7) and the [expression data](https://drive.google.com/open?id=1n9lPR7PQU78NcDmr4rjqHyMlrHby-J-3) with some changes. However I am getting the following error
![Screenshot from 2020-02-05 11-42-46](https://user-images.githubusercontent.com/33808607/73834817-ac8dc100-480c-11ea-8482-7d8fbf7aba14.png)

The `alpha must be positive` leads me to think that there is something wrong with the values in the tables. I see that ov.mRNA that you use in the example is normalized somehow. How did you performed the scaling? Also, how do you select the threshold values for discretizing? The empirical distribution option does not solve the issue.

Thanks!

**Comment by guanmingwu** [comment]
I am trying to run with your two data files. It is running for about 2 hours without error. Could you please take a look if you see a logging file called output.log in your Cytoscape installing folder and check if there is any error printed out there? We use z-score transformation to normalize mRNA expression data and choose the default parameters to discretize values.

**Comment by guanmingwu** [comment]
By the way, what version of ReactomeFIViz you are using? If you are not using the latest version, 7.2.1, could you please update to this version?
